apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              cpu: 800m
              memory: 800Mi