name: "Buf"

on:
  push:
    paths:
      - 'proto/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1.0.3
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}

  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-breaking-action@v1.1.3
        with:
          input: 'proto'
          against: 'https://github.com/levine824/monorepo.git#branch=master,ref=HEAD~1,subdir=proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
  
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - lint
      - breaking
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-push-action@v1.1.1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}